import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-[1300]`}
        style={{ scrollbarGutter: "stable" }}
      >
        <div className="flex bg-gray-100 gap-2 p-2 overflow-hidden relative transition-all max-h-[99vh]">
          {/* Sidebar Wrapper */}
          <div className="h-screen w-56  bg-white shadow-lg border-2 border-gray-200 z-20 rounded-2xl overflow-hidden">
            <div className="h-full overflow-y-auto scroll-smooth overflow-x-hidden">
              <Sidebar />
            </div>
          </div>

          {/* Content Wrapper */}
          <div className="flex flex-col flex-1 gap-2 ml-64 h-screen rounded-2xl overflow-hidden">
            <div className="bg-white border-2 border-gray-200 rounded-2xl">
              <Header />
            </div>

            {/* jab scroll bar lgana hai tu us k upr k container ko overflow hidden, rounded  */}
            <div className="mt-2 bg-white shadow border-2 border-gray-200 flex-1 rounded-2xl  overflow-hidden">
              <main className="p-6 h-full overflow-y-auto  scroll-smooth">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
